### ISSUE TITLE
Replay before services are injected

### ISSUE THREAD

**Issue by jeroenverfallie** [christianalfoni/cerebral-angular#6]
Just came across an issue involving angular services injection.

```
CEREBRAL - There was an error remembering state, it has been reset
```

Reproduction:

```
.config(function(cerebralProvider) {
    cerebralProvider.setController(controller);
    cerebralProvider.setServices(['$http']);
});
```
Use `$http` in an action that is replayed by the chrome extension.

You'll notice that the replay is done before the `$http` is injected, thus you get something in the lines of `cannot get 'get' of undefined` ($http.get)

**Comment by christianalfoni** [comment]
Ah, yes, Angular probably asynchronously fires up. So if the debugger tries to run some code it might do so while Angular is still firing up. This can easily be fixed by exposing a "runDebugger" method which is triggered by the different view layer implementations.

Okay, let me take a look at this later today, thanks for reporting! :-)

**Comment by jeroenverfallie** [comment]
:+1:

**Comment by christianalfoni** [comment]
Hi @jeroenverfallie , I believe this is fixed with latest version of Cerebral and Cerebral-Angular :-)
